"""
Django settings for Expense project.
Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from pathlib import Path
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================
# CORE / ENV
# ==========================
# Render will set environment variables. Locally you can ignore them.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret-key-change-me")

# DEBUG: True locally, False on Render
DEBUG = os.environ.get("DEBUG", "1") == "1"

# Render host fix (Bad Request 400 happens when host not allowed)
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".onrender.com",  # allows anything.onrender.com
]

# CSRF trusted origins (helps on Render + HTTPS)
CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
]


# ==========================
# APPS
# ==========================
INSTALLED_APPS = [
    # Django default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # your apps
    "accounts",
    "Tracker.apps.TrackerConfig",

    # DRF + JWT
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
]

# If you want Whitenoise to serve static during dev too, keep it.
# But DO NOT add "whitenoise.runserver_nostatic" unless you know why.
# That app can confuse dev if your static setup is not perfect.


# ==========================
# MIDDLEWARE
# ==========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # ✅ for Render/static

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ==========================
# URLS / TEMPLATES
# ==========================
ROOT_URLCONF = "Expense.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # You mostly use app templates (Tracker/templates), so this can stay:
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Expense.wsgi.application"


# ==========================
# DATABASE
# ==========================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ==========================
# PASSWORD VALIDATION
# ==========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ==========================
# I18N
# ==========================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ==========================
# STATIC FILES
# ==========================
STATIC_URL = "/static/"

# Because your css is in Tracker/static/..., Django will find it automatically in dev.
# STATIC_ROOT is needed for Render collectstatic.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Whitenoise storage for production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# (Optional but safe) ensures static discovery works well
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]


# ==========================
# AUTH REDIRECTS
# ==========================
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"


# ==========================
# DRF / JWT
# ==========================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}


# ==========================
# DEFAULT PRIMARY KEY FIELD
# ==========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"